### ISSUE TITLE
Update proper guid for installation

### ISSUE THREAD

**Issue by karmrajzala** [atans/yii2-history#1]
Please update proper installation guide for configure.

**Comment by atans** [comment]
Haha, It's still under  development, will be update,  thanks.

**Comment by atans** [comment]
If you would to install dev version

add ` "atans/yii2-history":"dev-master as 1.0.0",` to composer.json

then run 

```
composer update
```

**Comment by karmrajzala** [comment]
Ok. Thanks for this reply...
